---
name: cmpsc-302-spring-2019-lab9
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/www/:
    index.html:
        --exists
        --fragment "text/javascript" --count 1 --exact
        --fragment "js/country.js" --count 1 --exact
        --fragment "<html>" --count 1 --exact
        --fragment "<body>" --count 1 --exact
        --fragment "strong" --count 0 --exact
        --fragment "div" --count 0 --exact
        --fragment "TODO" --count 0 --exact
src/www/js:
    country.js:
        --exists
        --fragment "new Country(" --count 5 --exact
        --fragment "for (" --count 2 --exact
        --fragment "TODO" --count 0 --exact
# --> check the technical writing
# mdl is a Markdown linting tool
# proselint checks writing for common mistakes
writing/reflection.md:
    mdl
    proselint
    --paragraphs 5 --exact
    --fragment "Add Your Name Here" --count 0 --exact
    --words 50
# --> check the submission image exists
images/javascript_submission.png:
    --exists
# --> check the number of commits beyond a threshold
--commits 15
# --> check that the linter executes and produces 0 lines of output
--command "htmlhint src/www/index.html" --executes
--command "htmlhint src/www/index.html" --count 1 --exact
--command "htmlhint src/www/index.html" --fragment "no errors found" --count 1 --exact
